package edu.utm.bd.domain;

public class CompraHasProducto extends CompraHasProductoKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column compra_has_producto.CPCantidad
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	private Integer cpcantidad;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column compra_has_producto.CPCantidad
	 * @return  the value of compra_has_producto.CPCantidad
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public Integer getCpcantidad() {
		return cpcantidad;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column compra_has_producto.CPCantidad
	 * @param cpcantidad  the value for compra_has_producto.CPCantidad
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public void setCpcantidad(Integer cpcantidad) {
		this.cpcantidad = cpcantidad;
	}
}