package edu.utm.bd.domain;

public class CompraKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column compra.idCompra
     *
     * @mbg.generated Wed Apr 25 18:55:18 CDT 2018
     */
    private String idcompra;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column compra.Proveedor_id
     *
     * @mbg.generated Wed Apr 25 18:55:18 CDT 2018
     */
    private Integer proveedorId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column compra.idCompra
     *
     * @return the value of compra.idCompra
     *
     * @mbg.generated Wed Apr 25 18:55:18 CDT 2018
     */
    public String getIdcompra() {
        return idcompra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column compra.idCompra
     *
     * @param idcompra the value for compra.idCompra
     *
     * @mbg.generated Wed Apr 25 18:55:18 CDT 2018
     */
    public void setIdcompra(String idcompra) {
        this.idcompra = idcompra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column compra.Proveedor_id
     *
     * @return the value of compra.Proveedor_id
     *
     * @mbg.generated Wed Apr 25 18:55:18 CDT 2018
     */
    public Integer getProveedorId() {
        return proveedorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column compra.Proveedor_id
     *
     * @param proveedorId the value for compra.Proveedor_id
     *
     * @mbg.generated Wed Apr 25 18:55:18 CDT 2018
     */
    public void setProveedorId(Integer proveedorId) {
        this.proveedorId = proveedorId;
    }
}