package edu.utm.bd.domain;

import java.util.Date;

public class Compra extends CompraKey {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column compra.ComTotal
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	private Integer comtotal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column compra.ComFecha
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	private Date comfecha;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column compra.ComTotal
	 * @return  the value of compra.ComTotal
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public Integer getComtotal() {
		return comtotal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column compra.ComTotal
	 * @param comtotal  the value for compra.ComTotal
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public void setComtotal(Integer comtotal) {
		this.comtotal = comtotal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column compra.ComFecha
	 * @return  the value of compra.ComFecha
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public Date getComfecha() {
		return comfecha;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column compra.ComFecha
	 * @param comfecha  the value for compra.ComFecha
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public void setComfecha(Date comfecha) {
		this.comfecha = comfecha;
	}

	private String idcompra;
}