package edu.utm.bd.domain;

public class FacturaKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column factura.idFactura
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	private Integer idfactura;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column factura.Venta_Id
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	private String ventaId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column factura.idFactura
	 * @return  the value of factura.idFactura
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public Integer getIdfactura() {
		return idfactura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column factura.idFactura
	 * @param idfactura  the value for factura.idFactura
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public void setIdfactura(Integer idfactura) {
		this.idfactura = idfactura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column factura.Venta_Id
	 * @return  the value of factura.Venta_Id
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public String getVentaId() {
		return ventaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column factura.Venta_Id
	 * @param ventaId  the value for factura.Venta_Id
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public void setVentaId(String ventaId) {
		this.ventaId = ventaId;
	}
}