package edu.utm.bd.domain;

import java.util.Date;

public class Factura extends FacturaKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column factura.FacFecha
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	private Date facfecha;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column factura.FacNIF
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	private String facnif;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column factura.FacFecha
	 * @return  the value of factura.FacFecha
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public Date getFacfecha() {
		return facfecha;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column factura.FacFecha
	 * @param facfecha  the value for factura.FacFecha
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public void setFacfecha(Date facfecha) {
		this.facfecha = facfecha;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column factura.FacNIF
	 * @return  the value of factura.FacNIF
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public String getFacnif() {
		return facnif;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column factura.FacNIF
	 * @param facnif  the value for factura.FacNIF
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public void setFacnif(String facnif) {
		this.facnif = facnif;
	}
}