package edu.utm.bd.domain;

public class Producto extends ProductoKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producto.ProPrecioVenta
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	private Integer proprecioventa;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producto.ProPrecioCompra
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	private Integer propreciocompra;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producto.ProCantidad
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	private Integer procantidad;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producto.ProNombre
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	private String pronombre;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producto.ProPrecioVenta
	 * @return  the value of producto.ProPrecioVenta
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public Integer getProprecioventa() {
		return proprecioventa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producto.ProPrecioVenta
	 * @param proprecioventa  the value for producto.ProPrecioVenta
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public void setProprecioventa(Integer proprecioventa) {
		this.proprecioventa = proprecioventa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producto.ProPrecioCompra
	 * @return  the value of producto.ProPrecioCompra
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public Integer getPropreciocompra() {
		return propreciocompra;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producto.ProPrecioCompra
	 * @param propreciocompra  the value for producto.ProPrecioCompra
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public void setPropreciocompra(Integer propreciocompra) {
		this.propreciocompra = propreciocompra;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producto.ProCantidad
	 * @return  the value of producto.ProCantidad
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public Integer getProcantidad() {
		return procantidad;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producto.ProCantidad
	 * @param procantidad  the value for producto.ProCantidad
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public void setProcantidad(Integer procantidad) {
		this.procantidad = procantidad;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producto.ProNombre
	 * @return  the value of producto.ProNombre
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public String getPronombre() {
		return pronombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producto.ProNombre
	 * @param pronombre  the value for producto.ProNombre
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public void setPronombre(String pronombre) {
		this.pronombre = pronombre;
	}
}