package edu.utm.bd.domain;

public class Proveedor {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column proveedor.idProveedor
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	private Integer idproveedor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column proveedor.ProvNombre
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	private String provnombre;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column proveedor.idProveedor
	 * @return  the value of proveedor.idProveedor
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public Integer getIdproveedor() {
		return idproveedor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column proveedor.idProveedor
	 * @param idproveedor  the value for proveedor.idProveedor
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public void setIdproveedor(Integer idproveedor) {
		this.idproveedor = idproveedor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column proveedor.ProvNombre
	 * @return  the value of proveedor.ProvNombre
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public String getProvnombre() {
		return provnombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column proveedor.ProvNombre
	 * @param provnombre  the value for proveedor.ProvNombre
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public void setProvnombre(String provnombre) {
		this.provnombre = provnombre;
	}
}