package edu.utm.bd.domain;

public class Usuario {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usuario.idUsuario
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	private Integer idusuario;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usuario.UsuAdmin
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	private Boolean usuadmin;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usuario.idUsuario
	 * @return  the value of usuario.idUsuario
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public Integer getIdusuario() {
		return idusuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usuario.idUsuario
	 * @param idusuario  the value for usuario.idUsuario
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public void setIdusuario(Integer idusuario) {
		this.idusuario = idusuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usuario.UsuAdmin
	 * @return  the value of usuario.UsuAdmin
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public Boolean getUsuadmin() {
		return usuadmin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usuario.UsuAdmin
	 * @param usuadmin  the value for usuario.UsuAdmin
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public void setUsuadmin(Boolean usuadmin) {
		this.usuadmin = usuadmin;
	}
}