package edu.utm.bd.domain;

public class UsuarioWithBLOBs extends Usuario {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usuario.UsuNombre
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	private String usunombre;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usuario.UsuApellidos
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	private String usuapellidos;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usuario.UsuNick
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	private String usunick;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usuario.UsuPass
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	private String usupass;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usuario.UsuNombre
	 * @return  the value of usuario.UsuNombre
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public String getUsunombre() {
		return usunombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usuario.UsuNombre
	 * @param usunombre  the value for usuario.UsuNombre
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public void setUsunombre(String usunombre) {
		this.usunombre = usunombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usuario.UsuApellidos
	 * @return  the value of usuario.UsuApellidos
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public String getUsuapellidos() {
		return usuapellidos;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usuario.UsuApellidos
	 * @param usuapellidos  the value for usuario.UsuApellidos
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public void setUsuapellidos(String usuapellidos) {
		this.usuapellidos = usuapellidos;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usuario.UsuNick
	 * @return  the value of usuario.UsuNick
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public String getUsunick() {
		return usunick;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usuario.UsuNick
	 * @param usunick  the value for usuario.UsuNick
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public void setUsunick(String usunick) {
		this.usunick = usunick;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usuario.UsuPass
	 * @return  the value of usuario.UsuPass
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public String getUsupass() {
		return usupass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usuario.UsuPass
	 * @param usupass  the value for usuario.UsuPass
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public void setUsupass(String usupass) {
		this.usupass = usupass;
	}
}