package edu.utm.bd.domain;

public class VentaHasProducto extends VentaHasProductoKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column venta_has_producto.VPCantidad
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	private Integer vpcantidad;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column venta_has_producto.VPCantidad
	 * @return  the value of venta_has_producto.VPCantidad
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public Integer getVpcantidad() {
		return vpcantidad;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column venta_has_producto.VPCantidad
	 * @param vpcantidad  the value for venta_has_producto.VPCantidad
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public void setVpcantidad(Integer vpcantidad) {
		this.vpcantidad = vpcantidad;
	}
}