package edu.utm.bd.domain;

import java.util.Date;

public class Venta extends VentaKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column venta.VenFecha
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	private Date venfecha;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column venta.VenTotal
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	private Integer ventotal;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column venta.VenFecha
	 * @return  the value of venta.VenFecha
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public Date getVenfecha() {
		return venfecha;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column venta.VenFecha
	 * @param venfecha  the value for venta.VenFecha
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public void setVenfecha(Date venfecha) {
		this.venfecha = venfecha;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column venta.VenTotal
	 * @return  the value of venta.VenTotal
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public Integer getVentotal() {
		return ventotal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column venta.VenTotal
	 * @param ventotal  the value for venta.VenTotal
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public void setVentotal(Integer ventotal) {
		this.ventotal = ventotal;
	}
}